# Node IP of the Kubernetes cluster running ArgoCD
argocd_node_ip: "172.31.12.86"

# NodePort of ArgoCD HTTPS
argocd_nodeport_https: 30096

# TLS certificate paths
tls_cert_path: "/etc/ssl/certs/argocd.crt"
tls_key_path: "/etc/ssl/private/argocd.key"

# Server name for TLS (can be public IP if no DNS)
server_name: "argocd.example.com"
